### ISSUE TITLE
命令行的语法设计

### ISSUE THREAD

**Issue by seisman** [xumi1993/SFT#1]
`get_events.py` 中时间范围是通过选项 `-Yminyear/minmonth/minday/maxyear/maxmonth/maxday` 控制的。

为何要这样设计呢？直接参考 https://seiscode.iris.washington.edu/projects/ws-fetch-scripts 中的选项设计，将开始时间和结束时间作为两个参数，并且使用 `datetime` 模块来解析时间，感觉这样应该更简洁而且更不易出错。

**Comment by xumi1993** [comment]
哈哈 很有道理
我现在的想法是先按照IRIS-WS的参数设置把这几个命令写完，然后提供一些脚本，通过一个命令批量下载地震数据。
